### ISSUE TITLE
captured this error from light-bot auto build

### ISSUE THREAD

**Issue by stevehu** [networknt/light-eventuate-4j#50]
Don't know if this is just test case problem or system problem. 

```
Feb 19, 2018 1:51:29 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to localhost:3306 at /4 (sid:1519066260764, cid:15)
Feb 19, 2018 1:51:29 PM com.github.shyiko.mysql.binlog.BinaryLogClient notifyEventListeners
WARNING: com.networknt.eventuate.cdc.mysql.binlog.MySqlBinaryLogClient$$Lambda$34/1041547629@e5752c1 choked on Event{header=EventHeaderV4{timestamp=1519066289000, eventType=EXT_WRITE_ROWS, serverId=1, headerLength=19, dataLength=132, nextPosition=511, flags=0}, data=WriteRowsEventData{tableId=110, includedColumns={0, 1, 2}, rows=[
    [com.networknt.eventuate.test.domain.Account, 00000161af681471-ca0f690322830001, 00000161af681471-ca0f690322830000]
]}}
java.lang.ArrayIndexOutOfBoundsException: 4
	at com.networknt.eventuate.cdc.mysql.binlog.WriteRowsEventDataParser.getValue(WriteRowsEventDataParser.java:72)
	at com.networknt.eventuate.cdc.mysql.binlog.WriteRowsEventDataParser.parseEventData(WriteRowsEventDataParser.java:61)
	at com.networknt.eventuate.cdc.mysql.binlog.WriteRowsEventDataParser.parseEventData(WriteRowsEventDataParser.java:20)
	at com.networknt.eventuate.cdc.mysql.binlog.MySqlBinaryLogClient.lambda$start$0(MySqlBinaryLogClient.java:85)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1055)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:913)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by chenyan71** [comment]
re-run test case, and there is no warning message here:

Mar 01, 2018 4:08:47 PM com.github.shyiko.mysql.binlog.BinaryLogClient connect
INFO: Connected to localhost:3306 at /4 (sid:1519938455571, cid:1307)
16:08:47.321 [main]       DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection com.mysql.jdbc.JDBC4Connection@37bd68c3
16:08:47.378 [main]       DEBUG com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Reset (autoCommit) on connection com.mysql.jdbc.JDBC4Connection@37bd68c3
16:08:47.478 [blc-localhost:3306]       DEBUG c.n.e.c.m.b.MySqlBinaryLogClient - Got binlog event Event{header=EventHeaderV4{timestamp=1519417050000, eventType=EXT_WRITE_ROWS, serverId=1, headerLength=19, dataLength=224, nextPosition=27614, flags=0}, data=WriteRowsEventData{tableId=112, includedColumns={0, 1, 2, 3, 4, 5, 6, 7}, rows=[
    [00000161c4504164-acde480011220000, com.networknt.eventuate.test.domain.AccountCreatedEvent, {"initialBalance":1519417049423}, com.networknt.eventuate.test.domain.Account, 00000161c4504165-acde480011220000, null, null, 0]
]}}

**Comment by chenyan71** [comment]
It looks like the warning caused by the mySQL connection issue when the binlog start process
